---
title: 'Dot Product Classification'
date: "December 2, 2018"
output:
  html_document:
    theme: cerulean
    highlight: haddock
    fig_align: center
---


```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(magrittr)
library(pracma)
x = sample(1:100, 100, replace = TRUE)
y = sample(1:100, 100, replace = TRUE)
sign = y - x > 10

df = data.frame(x = x, y = y, sign = sign)
```

```{r}
ones = df %>% 
  filter(sign) %>% 
  select(-sign) %>% 
  t

negatives = df %>% 
  filter(!sign) %>% 
  select(-sign) %>% 
  t

c_plus = ones %>% 
  rowSums() %>% 
  divide_by(ncol(ones))

c_minus = negatives %>% 
  rowSums() %>% 
  divide_by(ncol(negatives))
```


```{r}
df_mat = df %>% 
  select(-sign)

result = sign(
  dot(t(df_mat)- (c_plus + c_minus)/2, 
  c_plus - c_minus))

sign[sign == 0] = -1
sign == result
```


```{r}

c_vec = (c_plus + c_minus)/2
X3 = c_vec[1]
X4 = c_vec[2]

d = data.frame(cbind(rbind(c_plus, c_minus), X3, X4, c(1, -1)))
colnames(d) = c("X1", "X2", "X3", "X4", "sign")


result_df = data.frame(df_mat, X3, X4)

slope = (c_plus-c_minus)[2]/(c_plus-c_minus)[1]
b = c_plus[2] - c_plus[1]*slope

mid_point = (c_plus + c_minus)/2
perp_slope = -1/slope
mid_b = X4 - X3*perp_slope

ggplot(df, aes(x = x, y = y, colour = sign)) +
  geom_point() +
  geom_point(data = d, aes(x = X1, y = X2, xend = X3, yend = X4, colour = as.character(sign), size = .5 )) +
  geom_abline(intercept = b, slope = slope) +
  geom_abline(intercept = mid_b, slope = perp_slope) +
  xlim(0, 100) +
  ylim(0, 100) +
  geom_segment(data = result_df, aes(x = x, y = y, xend = X3, yend = X4, colour = as.character(result)))
```


```{r}
```
