---
name: "Freddy Drennan"
title: "Bisection"
date: "November 19, 2019"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    theme: cerulean
    highlight: haddock
    fig_align: center
---


The bisection method solves for a root of $f(x) = 0$ by starting with two values that bracket the root.


```
REPEAT
  Set x_3 = (x_1 + x_2) / 2
  IF f(x_3) * f(x_1) < 0:
    SET x_2 = x_3
  ELSE Set x_1 = x_3
  ENDIF
UNTIL (|x_1 - x_2| < tolerance value) or f(x_3) = 0
```

```{r}
library(reticulate)
use_python('/Users/digitalfirstmedia/Documents/R/numerical_analysis/numerical_analysis/bin/python3')
```

### R
```{r}
bisect = function(f, x, y, tolerance = 1e-7) {
  repeat{
    z = (x + y) / 2
    if(f(z) * f(x) < 0) y = z
      else x = z
    if(abs(x - y) < tolerance) 
      break
  }
  z
}

bisect(sin, pi/2, 2*pi)

bisect(
  function(x) x^2 - 16,
  0, 10
)
```

```{r, echo = FALSE}
f = function(x) x^2 - 16
tolerance = 1e-7
x = 0
y = 10
x_vals = x
y_vals = y
z_vals = c(10)
repeat{
  z = (x + y) / 2
  x_vals = c(x_vals, x)
  y_vals = c(y_vals, y)
  z_vals = c(z_vals, z)
  if(f(z) * f(x) < 0) y = z
    else x = z
  if(abs(x - y) < tolerance) 
    break
}

```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
library(ggplot2)
library(tidyverse)
library(plotly)

results = data.frame(x = x_vals, y = y_vals, fx = f(x_vals), fy = f(y_vals),z = z_vals)
round(results, 4)
results %>%
ggplot() +
  stat_function(fun = f) +
  xlim(-1, 10) +
  ylim(-20, 20) + 
  geom_segment(aes(x = x, y = fx, xend = y, yend = fy, colour = z)) -> 
  ggp

ggplotly(ggp)
  
```

### Python
```{python}
import numpy as np

def bisect(func, x, y, tolerance = 1e-7):
  while True:
    z = (x + y) / 2
    if func(z) * func(x) < 0:
      y = z
    else: x = z
    if np.abs(x - y) < tolerance:
      break
  return z
  

print(
  bisect(lambda x: np.sin(x), 3, 3.4)
)


print(
  bisect(lambda x: x ** 2 - 16, 2, 8)
)

```
